[package]
edition = "2021"
name = "vwap-impl"
version = "0.1.0"

[workspace]

[dependencies]
dummy = {path = "../../dummy"}
ethers-core = "2.0.14"
# use experimental feature of std support
risc0-zkvm = {version = "0.21.0", default-features = false, features = ["std"]}
