[package]
edition = "2021"
name = "vwap-impl"
version = "0.1.0"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = {version = "0.21.0", default-features = false}
