[package]
edition = "2021"
name = "host"
version = "0.1.0"

[dependencies]
dummy = {path = "../dummy"}
ethers-core = "2.0.14"
methods = {path = "../methods"}
risc0-zkvm = {version = "0.21.0"}
serde = "1.0"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
