[package]
edition = "2021"
name = "methods"
version = "0.1.0"

[build-dependencies]
risc0-build = {version = "0.21.0"}

[dependencies]
ethers = {version = "2.0.14", features = ["rustls", "ws"]}

[package.metadata.risc0]
methods = ["guest"]
